import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/naviagtion/NavBar";
import SideBar from "@/components/naviagtion/SideBar";
import BottomBar from "@/components/naviagtion/BottomBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* show title and notification toggle */}
      <Navbar />

      <body className="flex min-h-screen flex-col md:flex-row">
    

        {/* Desktop Sidebar (Left) */}
        <SideBar />

        <main className="flex-1 pb-16 md:pb-0 md:pl-64">
          {children}
        </main>

        {/* Mobile Bottom Nav */}
        <BottomBar />
      </body>
    </html>
  );
}
